#!/bin/sh

if [ -z "$CUDA_VISIBLE_DEVICES" -a -n "$OMPI_COMM_WORLD_LOCAL_RANK" -a -n "$OMPI_COMM_WORLD_LOCAL_SIZE" ]; then
  NB_GPUS=$(nvidia-smi -L | wc -l)
  if [ -n "$NB_GPUS" -a "$NB_GPUS" -ge "$OMPI_COMM_WORLD_LOCAL_SIZE" ]; then
    export CUDA_VISIBLE_DEVICES=$OMPI_COMM_WORLD_LOCAL_RANK
    i=1
    while [ $((OMPI_COMM_WORLD_LOCAL_RANK + i * OMPI_COMM_WORLD_LOCAL_SIZE)) -lt $NB_GPUS ]; do    
      export CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_DEVICES",$((OMPI_COMM_WORLD_LOCAL_RANK + i * OMPI_COMM_WORLD_LOCAL_SIZE))
      i=$((i+1))
    done
  fi
fi

ne=$1
shift

exec $ne $*
